const opportunities = [
 {type:'vc',kind:'Venture fellowship',name:'Thrive Capital Fellowship',desc:'A paid 10-week summer experience for current college students to work alongside a leading NYC venture firm.',meta:'College students · Summer',url:'https://fellows.thrivecap.com/',accent:'violet',status:'2026 cohort'},
 {type:'vc',kind:'Venture program',name:'Contrary Venture Partner',desc:'A network for ambitious student builders and community leaders interested in startups and venture.',meta:'Students · Campus network',url:'https://applications.contrary.com/?program=Venture+Partner+Program',accent:'coral',status:'Apply'},
 {type:'vc',kind:'Campus investing',name:'Columbia Venture Fellows',desc:'A selective Columbia Business School program for students pursuing careers in venture capital.',meta:'CBS students · Coursework',url:'https://business.columbia.edu/lang/student-and-alumni-programming/invest/columbia-venture-fellows',accent:'blue',status:'Columbia'},
 {type:'vc',kind:'VC fellowship',name:'HBCUvc VC Fellowship',desc:'Connects HBCU-affiliated graduate students with VC firms seeking summer and school-year interns.',meta:'Graduate students · VC track',url:'https://www.hbcu.vc/programs/vc-fellowship',accent:'yellow',status:'Seasonal'},
 {type:'jobs',kind:'Startup jobs',name:'Built In NYC',desc:'Search thousands of NYC startup and tech companies, with company profiles and current openings.',meta:'NYC · All functions',url:'https://www.builtinnyc.com/',accent:'green',status:'Live board'},
 {type:'jobs',kind:'Startup jobs',name:'Wellfound',desc:'Early-stage companies hiring across product, engineering, operations, growth, and more.',meta:'Startups · Remote + NYC',url:'https://wellfound.com/jobs',accent:'coral',status:'Live board'},
 {type:'jobs',kind:'Impact internships',name:'NYC SBS Excelerator',desc:'A selective summer fellowship for students working on projects that expand opportunity for NYC businesses.',meta:'Undergrad + grad · Summer',url:'https://www.nyc.gov/site/sbs/about/excelerator.page',accent:'blue',status:'Public sector'},
 {type:'programs',kind:'Accelerator',name:'Techstars NYC',desc:'A three-month mentorship-driven accelerator designed to help founders reach product-market fit.',meta:'Founders · Hybrid NYC',url:'https://www.techstars.com/accelerators/nyc',accent:'violet',status:'2027 applications'},
 {type:'programs',kind:'Founder fellowship',name:'NYCEDC Founder Fellowship',desc:'A city-backed program linking diverse founders to capital, networks, and resources in NYC.',meta:'Founders · NYC ecosystem',url:'https://edc.nyc/founder-fellowship',accent:'yellow',status:'Annual cohort'},
 {type:'programs',kind:'Student accelerator',name:'PearX',desc:'An accelerator for student founders that pairs an immersive build program with Pear VC’s network.',meta:'Student founders · Build',url:'https://pear.vc/pearx-application/',accent:'green',status:'Apply'},
 {type:'programs',kind:'Accelerator',name:'ERA',desc:'NYC’s Entrepreneurs Roundtable Accelerator supports early-stage companies building in New York.',meta:'Founders · NYC',url:'https://www.eranyc.com/',accent:'coral',status:'Cohort-based'},
 {type:'programs',kind:'Founder network',name:'Columbia Startup Lab',desc:'A co-working and event hub for Columbia alumni founders building companies in NYC.',meta:'Columbia alumni · SoHo',url:'https://entrepreneurship.columbia.edu/startup-lab/',accent:'blue',status:'Community'}
];
const cards = document.querySelector('#cards');
function render(filter='all') { const items = filter === 'all' ? opportunities : opportunities.filter(o => o.type === filter); cards.innerHTML = items.map((o,i) => `<a class="card ${o.accent}" style="--i:${i}" href="${o.url}" target="_blank" rel="noopener"><div class="card-top"><span>${o.kind}</span><b>${o.status}</b></div><div class="card-body"><h3>${o.name}</h3><p>${o.desc}</p></div><div class="card-foot"><small>${o.meta}</small><strong>↗</strong></div></a>`).join(''); }
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');render(btn.dataset.filter)})); render();
